<?php

namespace TennisBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindOneById($id){
        $qb = $this->createQueryBuilder('t');
        $qb->select('t')
            ->where('t.id = :id')
            ->join('t.listuser','l')
            ->addSelect('l')
            ->setParameter('id', $id);
        return $qb->getQuery()->getSingleResult();

    }
}
